### PR TITLE
Run only integration-tests on release test

### PR DESCRIPTION
**Pull request by upsuper**
And try to run with two threads.

This should be much faster than the current setting.

### CODE REVIEW

**Comment by mrijkeboer** [comment]
Why would this be faster (except for using 2 threads)? It will only skip the fast unit tests in release mode.

**Comment by mrijkeboer** [comment]
If you want to take this route you should skip the integration_tests in the debug mode and only run them in release. Why not run all the tests in release mode and skip debug mode?

**Comment by upsuper** [comment]
In general, I think we want to run all tests in debug mode, so that we can catch any debug assertion and unexpected integer overflow in code. But those slow tests are... slow, but we still want to run them, so we can try run them in release mode.

The main reason I'm skipping the fast tests in release is that you cannot specify test threads for different tests separately, which means you would only be able to run two tests parallelly even if you can run four. So the fast tests may not be worth running in release mode.

But you cannot run slow tests with four threads because that would eat up all memory Travis-CI provides, and causes the test to be killed.

**Comment by mrijkeboer** [comment]
The explains, thanks.

**Pull request merged**
