### PR TITLE
Make parallellism optional via feature flag

### PR DESCRIPTION
**Pull request by djc**
Since `ThreadMode::Parallel` isn't used by default, it might make sense to make the dependency optional.

### CODE REVIEW

**Comment by djc** [comment]
@mrijkeboer friendly reminder?

**Comment by djc** [comment]
Thanks! Would you mind pushing out a release?

**Comment by mrijkeboer** [comment]
Hi @djc, thanks for your pull request and sorry for the delay. I've pushed version 0.8.0 to crates.io.

**Comment by djc** [comment]
No worries! Thanks for the quick response.

**Pull request merged**
